In [15]:
import numpy as np
import pandas as pd
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense
from sklearn.metrics import f1_score, mean_squared_error

In [2]:
# Load the IMDB dataset
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

# Preprocess the data: pad sequences to a maximum length of 100
maxlen = 100
train_data = pad_sequences(train_data, maxlen=maxlen)
test_data = pad_sequences(test_data, maxlen=maxlen)

In [3]:
model = Sequential([
    Embedding(10000, 32, input_length=maxlen),
    Flatten(),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

C:\Users\heman\anaconda3\lib\site-packages\keras\src\layers\core\embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [4]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [5]:
model.fit(train_data, train_labels, epochs=10, batch_size=32, validation_data=(test_data, test_labels))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 12ms/step - accuracy: 0.6958 - loss: 0.5399 - val_accuracy: 0.8414 - val_loss: 0.3577
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9411 - loss: 0.1673 - val_accuracy: 0.8269 - val_loss: 0.4311
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9945 - loss: 0.0295 - val_accuracy: 0.8258 - val_loss: 0.5504
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9990 - loss: 0.0059 - val_accuracy: 0.8281 - val_loss: 0.6312
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8324 - val_loss: 0.6593
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 1.0000 - loss: 3.1684e-04 - val_accuracy: 0.8333 - val_loss: 0.6910
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 1.0000 - loss: 1.6984e-04 - val_accuracy: 0.8345 - val_loss: 0.7206
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 1.0000 - loss: 9.9916e-

In [6]:
test_loss, test_accuracy = model.evaluate(test_data, test_labels)
print(f'Test Accuracy: {test_accuracy}')

782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8343 - loss: 0.8216
Test Accuracy: 0.8358399868011475


In [8]:
pred=model.predict(test_data)

782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step


In [9]:
pred

array([[4.0430982e-06],
       [9.9999577e-01],
       [9.6215206e-01],
       ...,
       [1.9574791e-05],
       [2.1459800e-05],
       [8.9292336e-01]], dtype=float32)

In [10]:
# Apply thresholding to convert probabilities into binary predictions
threshold = 0.5
binary_pred = np.where(pred > threshold, 1, 0)

In [11]:
binary_pred

array([[0],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [13]:
test_labels

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [18]:
ps=[]
for i in binary_pred:
    ps.append(i[0])
d= pd.DataFrame({'actual':test_labels, 'predicted':ps})
d

actual  predicted
0           0          0
1           1          1
2           1          1
3           0          0
4           1          1
...       ...        ...
24995       1          1
24996       1          0
24997       0          0
24998       0          0
24999       0          1

[25000 rows x 2 columns]